### ISSUE TITLE
老板 打扰了 问一下

### ISSUE THREAD

**Issue by lqh301619** [net-byte/socks5-server#2]
老板在吗？请问，端口是1080 ，用户名密码是多少？ 我填写root  和123456连不上。
防火墙1080也打开了

**Comment by net-byte** [comment]
部署：
docker run  -d --restart=always \
-p 1080:1080 -p 1080:1080/udp --name socks5-server netbyte/socks5-server -l :1080 -u root -p 123456
测试：
curl -x socks5://root:123456@127.0.0.1:1080 https://ifconfig.me/
