### ISSUE TITLE
请问TLS启用后怎么连接啊？

### ISSUE THREAD

**Issue by daltonxiong** [net-byte/socks5-server#3]
1.curl应该怎么配置才能测试连接呢？
2.不配置用户名和密码的情况下SwitchyOmega应该怎么配置?

以下命令超时
```
curl --proxy socks5://localhost:33080 --proxy-key server.key --proxy-cert server.crt http://ifcfg.cn
```

**Comment by net-byte** [comment]
SwitchyOmega和curl无法直接使用 socks5 over tls，中间需要一个tcp to tls 代理，我写了一个tcptun。
流程：
SwitchyOmega or curl -> tcptun-client -> socks5-server

部署客户端：
docker run -d --restart=always  \ 
--name tcptun-client -p 2000:2000 netbyte/tcptun -l :2000 -s server-ip:1080 -tls

部署服务端：
docker run  -d --restart=always \
-p 1080:1080 -p 1080:1080/udp --name socks5-server netbyte/socks5-server -l :1080 -tls -sk /app/certs/server.key -sp /app/certs/server.pem
