### ISSUE TITLE
snmpwalk

### ISSUE THREAD

**Issue by contactsports** [net-byte/socks5-server#4]
hi, first off, great job and cool app.

using your server with dante/socksify client, tcp connections work fine, but running snmpwalk to query a mib does not seem to work.  do not have ability to capture network traffic on server so don't know how udp ports are mapped.  should be connecting to 161.  do you have a way to test if an snmp query through your server is working properly?

thanks!

**Comment by net-byte** [comment]
hi,there is a bug when binding address is 0.0.0.0:1080,I fixed it.
